// frontend/src/views/Home.vue
<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { useRouter } from 'vue-router'
import { Button, Tabs, TabsList, TabsTrigger, TabsContent } from 'nom-ui'
import { useWalletStore } from '../stores/wallet'
import { useBalancesStore } from '../stores/balances'
import { useTxsStore } from '../stores/txs'
import { useUnreceivedStore } from '../stores/unreceived'
import { usePlasmaStore } from '../stores/plasma'
import { usePillarStore } from '../stores/pillar'
import { useNodeStore } from '../stores/node'
import { useTxStore } from '../stores/tx'
import * as Cfg from '../../wailsjs/go/app/ConfigService'
import * as N from '../../wailsjs/go/app/NodeService'
import AccountSwitcher from '../components/AccountSwitcher.vue'
import BalanceCard from '../components/BalanceCard.vue'
import ActionCard from '../components/ActionCard.vue'
import StatusStrip from '../components/StatusStrip.vue'
import TokensPanel from '../components/TokensPanel.vue'
import RewardsPanel from '../components/panels/RewardsPanel.vue'
import PlasmaPanel from '../components/panels/PlasmaPanel.vue'
import PillarPanel from '../components/panels/PillarPanel.vue'
import StakingPanel from '../components/panels/StakingPanel.vue'
import SentinelsPanel from '../components/panels/SentinelsPanel.vue'
import AcceleratorPanel from '../components/panels/AcceleratorPanel.vue'
import TxHistory from '../components/TxHistory.vue'
import SendModal from '../components/SendModal.vue'
import ReceiveModal from '../components/ReceiveModal.vue'
import NomConfirm from '../components/NomConfirm.vue'

const router = useRouter()
const wallet = useWalletStore()
const balances = useBalancesStore()
const txs = useTxsStore()
const unreceived = useUnreceivedStore()
const plasma = usePlasmaStore()
const pillar = usePillarStore()
const node = useNodeStore()
const tx = useTxStore()

const TABS = ['Tokens', 'Rewards', 'Plasma', 'Pillar', 'Staking', 'Sentinels', 'Accelerator']
const active = ref('Tokens')
const sendOpen = ref(false)
const receiveOpen = ref(false)
const autoReceive = ref(false)

// Reset the tx flow when switching tabs (mirrors the Svelte resetTx on tab
// change) so a half-built block doesn't leak across panels.
watch(active, () => tx.reset())

const znn = computed(() => balances.items.find((b) => b.symbol === 'ZNN'))
const qsr = computed(() => balances.items.find((b) => b.symbol === 'QSR'))

async function refresh() {
  await Promise.all([
    balances.load(),
    plasma.refresh(),
    pillar.refreshDelegation(),
    txs.load(),
    unreceived.load(),
  ])
}

// Auto-receive is bound to a single account on the backend (it subscribes +
// sweeps for whichever address is active when it starts). startAR() always
// stops first so it re-points at the CURRENT active account — StartAutoReceive
// alone would early-return as "already running" and keep watching the old one.
let arAccount = -1
async function startAR() {
  await N.StopAutoReceive()
  await N.StartAutoReceive()
  arAccount = wallet.activeIndex
}
async function stopAR() {
  await N.StopAutoReceive()
  arAccount = -1
}

async function toggleAutoReceive() {
  try {
    const s = await Cfg.GetSettings()
    s.autoReceive = autoReceive.value
    await Cfg.SetSettings(s)
    if (autoReceive.value) await startAR()
    else await stopAR()
  } catch {}
}

async function onActiveChange(active: number) {
  refresh()
  // Follow account switches: re-sweep + re-subscribe for the new account.
  if (autoReceive.value && active !== arAccount) await startAR()
}

// Drive onActiveChange off the active account index (the Svelte `$: if
// ($wallet.active >= 0)` reactive statement).
watch(
  () => wallet.activeIndex,
  (i) => { if (i >= 0) onActiveChange(i) },
)

onMounted(async () => {
  node.initEvents(refresh)
  refresh()
  try {
    autoReceive.value = (await Cfg.GetSettings()).autoReceive
    if (autoReceive.value) await startAR() // resume (subscription doesn't survive a restart)
  } catch {}
})
</script>

<template>
  <div class="mx-auto mt-6 w-[56rem] max-w-full space-y-4 px-4">
    <div class="flex items-center justify-between">
      <AccountSwitcher />
      <div class="flex items-center gap-3">
        <label class="flex items-center gap-1 text-xs text-muted-foreground">
          <input type="checkbox" v-model="autoReceive" @change="toggleAutoReceive" /> Auto-receive
        </label>
        <Button variant="ghost" aria-label="Settings" @click="router.push('/settings')">Settings</Button>
        <Button variant="ghost" @click="wallet.lock()">Lock</Button>
      </div>
    </div>

    <div class="grid grid-cols-2 gap-3 sm:grid-cols-4">
      <BalanceCard symbol="ZNN" :amount="znn?.amount ?? '0'" :decimals="znn?.decimals ?? 8" tint="green" />
      <BalanceCard symbol="QSR" :amount="qsr?.amount ?? '0'" :decimals="qsr?.decimals ?? 8" tint="blue" />
      <ActionCard label="Send" direction="send" @click="sendOpen = true" />
      <ActionCard
        label="Receive"
        direction="receive"
        :badge="unreceived.items.length"
        @click="receiveOpen = true"
      />
    </div>

    <StatusStrip />

    <div class="rounded border border-border bg-card">
      <Tabs v-model="active">
        <TabsList class="w-full justify-start overflow-x-auto">
          <TabsTrigger v-for="t in TABS" :key="t" :value="t">{{ t }}</TabsTrigger>
        </TabsList>
        <TabsContent value="Tokens"><TokensPanel /></TabsContent>
        <TabsContent value="Rewards"><RewardsPanel /></TabsContent>
        <TabsContent value="Plasma"><PlasmaPanel /></TabsContent>
        <TabsContent value="Pillar"><PillarPanel /></TabsContent>
        <TabsContent value="Staking"><StakingPanel /></TabsContent>
        <TabsContent value="Sentinels"><SentinelsPanel /></TabsContent>
        <TabsContent value="Accelerator"><AcceleratorPanel /></TabsContent>
      </Tabs>
    </div>

    <TxHistory />
  </div>

  <SendModal v-model:open="sendOpen" />
  <ReceiveModal v-model:open="receiveOpen" />
  <!-- Global confirm for panel-triggered tx. Gated so it never collides with the
       Send/Receive dialogs, which render their own TxModal. -->
  <NomConfirm v-if="!sendOpen && !receiveOpen" />
</template>

// frontend/src/routes/Home.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { wallet, lock } from '../lib/stores/wallet'
  import { balances, loadBalances } from '../lib/stores/balances'
  import { initNodeEvents } from '../lib/stores/node'
  import { view } from '../lib/stores/nav'
  import { tx, resetTx } from '../lib/stores/tx'
  import { refreshPlasma } from '../lib/stores/plasma'
  import { refreshPillars } from '../lib/stores/pillar'
  import { loadTxs } from '../lib/stores/txs'
  import { unreceived, loadUnreceived } from '../lib/stores/unreceived'
  import * as Cfg from '../../wailsjs/go/app/ConfigService'
  import * as N from '../../wailsjs/go/app/NodeService'
  import AccountSwitcher from '../lib/components/AccountSwitcher.svelte'
  import BalanceCard from '../lib/components/BalanceCard.svelte'
  import ActionCard from '../lib/components/ActionCard.svelte'
  import StatusStrip from '../lib/components/StatusStrip.svelte'
  import Tabs from '../lib/components/ui/Tabs.svelte'
  import Button from '../lib/components/ui/Button.svelte'
  import SendModal from '../lib/components/SendModal.svelte'
  import ReceiveModal from '../lib/components/ReceiveModal.svelte'
  import TokensPanel from '../lib/components/panels/TokensPanel.svelte'
  import RewardsPanel from '../lib/components/panels/RewardsPanel.svelte'
  import PlasmaPanel from '../lib/components/panels/PlasmaPanel.svelte'
  import PillarPanel from '../lib/components/panels/PillarPanel.svelte'
  import StakingPanel from '../lib/components/panels/StakingPanel.svelte'
  import SentinelsPanel from '../lib/components/panels/SentinelsPanel.svelte'
  import AcceleratorPanel from '../lib/components/panels/AcceleratorPanel.svelte'
  import TxModal from '../lib/components/TxModal.svelte'
  import TxResult from '../lib/components/TxResult.svelte'
  import TxHistory from '../lib/components/TxHistory.svelte'

  const TABS = ['Tokens', 'Rewards', 'Plasma', 'Pillar', 'Staking', 'Sentinels', 'Accelerator']
  let active = 'Tokens'
  let sendOpen = false
  let receiveOpen = false
  let autoReceive = false
  let prevTab = active

  $: if (active !== prevTab) { prevTab = active; resetTx() }

  function bal(sym: string) { return $balances.find((b) => b.symbol === sym) }
  async function refresh() { await Promise.all([loadBalances(), refreshPlasma(), refreshPillars(), loadTxs(), loadUnreceived()]) }
  onMount(async () => {
    initNodeEvents(refresh)
    refresh()
    try {
      autoReceive = (await Cfg.GetSettings()).autoReceive
      // Resume auto-receive if it was enabled (the setting persists, the
      // subscription does not survive a restart).
      if (autoReceive) await N.StartAutoReceive()
    } catch {}
  })
  $: if ($wallet.active >= 0) refresh()
  async function toggleAutoReceive() {
    try {
      const s = await Cfg.GetSettings(); s.autoReceive = autoReceive; await Cfg.SetSettings(s)
      if (autoReceive) await N.StartAutoReceive(); else await N.StopAutoReceive()
    } catch {}
  }
</script>

<div class="mx-auto mt-6 w-[56rem] max-w-full space-y-4 px-4">
  <div class="flex items-center justify-between">
    <AccountSwitcher />
    <div class="flex items-center gap-3">
      <label class="flex items-center gap-1 text-xs text-muted">
        <input type="checkbox" bind:checked={autoReceive} on:change={toggleAutoReceive} /> Auto-receive
      </label>
      <Button variant="ghost" aria-label="Settings" on:click={() => view.set('settings')}>Settings</Button>
      <Button variant="ghost" on:click={lock}>Lock</Button>
    </div>
  </div>

  <div class="grid grid-cols-2 gap-3 sm:grid-cols-4">
    <BalanceCard symbol="ZNN" amount={bal('ZNN')?.amount ?? '0'} decimals={bal('ZNN')?.decimals ?? 8} tint="green" />
    <BalanceCard symbol="QSR" amount={bal('QSR')?.amount ?? '0'} decimals={bal('QSR')?.decimals ?? 8} tint="blue" />
    <ActionCard label="Send" direction="send" on:click={() => (sendOpen = true)} />
    <ActionCard label="Receive" direction="receive" badge={$unreceived.length} on:click={() => (receiveOpen = true)} />
  </div>

  <StatusStrip />

  <div class="rounded border border-border bg-surface">
    <Tabs tabs={TABS} bind:active />
    {#if active === 'Tokens'}<TokensPanel />
    {:else if active === 'Rewards'}<RewardsPanel />
    {:else if active === 'Plasma'}<PlasmaPanel />
    {:else if active === 'Pillar'}<PillarPanel />
    {:else if active === 'Staking'}<StakingPanel />
    {:else if active === 'Sentinels'}<SentinelsPanel />
    {:else if active === 'Accelerator'}<AcceleratorPanel />{/if}
  </div>

  <TxHistory />
</div>

<SendModal bind:open={sendOpen} />
<ReceiveModal bind:open={receiveOpen} />

<!-- SendModal renders its own TxModal/TxResult inside its overlay; suppress the
     global one while it's open so the Send confirm isn't double-rendered. -->
{#if $tx.status === 'awaiting' && $tx.preview && !sendOpen}<TxModal />{/if}
{#if $tx.status === 'done' && !sendOpen}<TxResult />{/if}
