// frontend/src/lib/components/ui/Field.svelte
<script lang="ts">
  export let label = ''
  export let hint = ''
  export let error = ''
</script>
<label class="block space-y-1">
  {#if label}<span class="text-sm text-text">{label}</span>{/if}
  <slot />
  {#if error}<span class="block text-xs text-error">{error}</span>
  {:else if hint}<span class="block text-xs text-muted">{hint}</span>{/if}
</label>

// frontend/src/components/Field.vue
<script setup lang="ts">
defineProps<{ label?: string; hint?: string; error?: string }>()
</script>

<template>
  <label class="block space-y-1">
    <span v-if="label" class="text-sm text-foreground">{{ label }}</span>
    <slot />
    <span v-if="error" class="block text-xs text-destructive" role="alert">{{ error }}</span>
    <span v-else-if="hint" class="block text-xs text-muted-foreground">{{ hint }}</span>
  </label>
</template>
