// frontend/src/components/panels/PillarPanel.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { storeToRefs } from 'pinia'
import { Input, Button } from 'nom-ui'
import * as Nom from '../../../wailsjs/go/app/NomService'
import { usePillarStore } from '../../stores/pillar'
import { useTxStore } from '../../stores/tx'
import { formatAmount } from '../../lib/format'

const pillar = usePillarStore()
const tx = useTxStore()

const { pillars, delegation, reward: pillarReward } = storeToRefs(pillar)

const search = ref('')
const error = ref('')

const rewardZero = computed(
  () => !pillarReward.value || (pillarReward.value.znn === '0' && pillarReward.value.qsr === '0'),
)
const delegated = computed(() => !!delegation.value && delegation.value.name !== '')
const filtered = computed(() =>
  (pillars.value ?? [])
    .filter((p) => p.name.toLowerCase().includes(search.value.trim().toLowerCase()))
    .sort((a, b) => a.rank - b.rank),
)

// NoM-confirm pattern: prepare the call, then hand the preview to the global
// NomConfirm dialog via tx.awaitConfirm. The panel renders no modal itself.
async function delegate(name: string) {
  error.value = ''
  try {
    tx.awaitConfirm(await Nom.PrepareDelegate(name))
  } catch (e: unknown) {
    error.value = e instanceof Error ? e.message : String(e)
  }
}
async function undelegate() {
  error.value = ''
  try {
    tx.awaitConfirm(await Nom.PrepareUndelegate())
  } catch (e: unknown) {
    error.value = e instanceof Error ? e.message : String(e)
  }
}
async function collect() {
  error.value = ''
  try {
    tx.awaitConfirm(await Nom.PrepareCollectPillarReward())
  } catch (e: unknown) {
    error.value = e instanceof Error ? e.message : String(e)
  }
}

onMounted(() => pillar.refresh())
watch(
  () => tx.status,
  (s) => {
    if (s === 'done') pillar.refresh()
  },
)
</script>

<template>
  <div class="space-y-4 p-4">
    <section class="space-y-2 rounded-lg border border-border bg-card p-4">
      <h2 class="text-sm font-medium text-foreground">Your delegation</h2>
      <div v-if="delegated && delegation" class="flex items-center justify-between text-sm">
        <p>
          Delegated to <span class="font-mono text-primary">{{ delegation.name }}</span> · weight
          <span class="font-mono">{{ formatAmount(delegation.weight, 8) }} ZNN</span>
        </p>
        <Button variant="outline" aria-label="undelegate" @click="undelegate">Undelegate</Button>
      </div>
      <p v-else class="text-xs text-muted-foreground">Not delegated.</p>

      <div v-if="pillarReward" class="flex items-center justify-between text-sm">
        <p class="text-muted-foreground">
          Uncollected reward
          <span class="font-mono text-foreground">{{ formatAmount(pillarReward.znn, 8) }} ZNN</span> ·
          <span class="font-mono text-foreground">{{ formatAmount(pillarReward.qsr, 8) }} QSR</span>
        </p>
        <Button :disabled="rewardZero" @click="collect">Collect</Button>
      </div>
    </section>

    <section class="space-y-3 rounded-lg border border-border bg-card p-4">
      <div class="flex items-center justify-between gap-3">
        <h2 class="text-sm font-medium text-foreground">Pillars</h2>
        <span class="text-xs text-muted-foreground">Sorted by Rank</span>
      </div>
      <Input v-model="search" placeholder="Search pillars" aria-label="search pillars" />

      <div class="space-y-1">
        <div
          v-for="p in filtered"
          :key="p.name"
          class="flex items-center justify-between gap-3 rounded-md border border-transparent px-2 py-2 hover:border-border hover:bg-muted"
        >
          <div class="flex min-w-0 items-baseline gap-3">
            <span class="shrink-0 font-mono text-xs text-muted-foreground">#{{ p.rank }}</span>
            <span class="truncate text-sm text-foreground">{{ p.name }}</span>
            <span
              v-if="p.name === delegation?.name"
              class="shrink-0 rounded bg-primary/15 px-1.5 py-0.5 text-[10px] font-medium text-primary"
              >current</span
            >
          </div>
          <div class="flex shrink-0 items-center gap-4">
            <span class="text-xs text-primary">{{ p.delegateRewardPercent }}% APR</span>
            <span class="font-mono text-xs text-muted-foreground"
              >{{ formatAmount(p.weight, 8) }} ZNN</span
            >
            <Button :aria-label="`delegate to ${p.name}`" @click="delegate(p.name)">Delegate</Button>
          </div>
        </div>
        <p v-if="filtered.length === 0" class="text-xs text-muted-foreground">No pillars.</p>
      </div>
    </section>

    <p v-if="error" class="text-sm text-destructive" role="alert">{{ error }}</p>

    <p v-if="tx.status === 'preparing'" class="text-muted-foreground">Preparing… (PoW if required)</p>
    <p v-if="tx.status === 'error'" class="text-destructive" role="alert">{{ tx.error }}</p>
  </div>
</template>

// frontend/src/lib/components/panels/PillarPanel.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import * as Nom from '../../../../wailsjs/go/app/NomService'
  import { pillars, delegation, pillarReward, refreshPillars } from '../../stores/pillar'
  import { tx, awaitConfirm } from '../../stores/tx'
  import { formatAmount } from '../../format'
  import Input from '../ui/Input.svelte'
  import Button from '../ui/Button.svelte'

  let search = ''
  let error = ''

  onMount(refreshPillars)
  $: rewardZero = !$pillarReward || ($pillarReward.znn === '0' && $pillarReward.qsr === '0')
  $: delegated = !!$delegation && $delegation.name !== ''
  $: filtered = ($pillars ?? [])
    .filter((p) => p.name.toLowerCase().includes(search.trim().toLowerCase()))
    .sort((a, b) => a.rank - b.rank)
  $: if ($tx.status === 'done') refreshPillars()

  async function delegate(name: string) {
    error = ''
    try { awaitConfirm((await Nom.PrepareDelegate(name)) as any) } catch (e: any) { error = e?.message ?? String(e) }
  }
  async function undelegate() {
    error = ''
    try { awaitConfirm((await Nom.PrepareUndelegate()) as any) } catch (e: any) { error = e?.message ?? String(e) }
  }
  async function collect() {
    error = ''
    try { awaitConfirm((await Nom.PrepareCollectPillarReward()) as any) } catch (e: any) { error = e?.message ?? String(e) }
  }
</script>

<div class="space-y-4 p-4">
  <section class="space-y-2 rounded-lg border border-border bg-surface p-4">
    <h2 class="text-sm font-medium text-text">Your delegation</h2>
    {#if delegated}
      <div class="flex items-center justify-between text-sm">
        <p>Delegated to <span class="font-mono text-accent">{$delegation.name}</span> · weight <span class="font-mono">{formatAmount($delegation.weight, 8)} ZNN</span></p>
        <Button variant="outline" on:click={undelegate} aria-label="undelegate">Undelegate</Button>
      </div>
    {:else}
      <p class="text-xs text-muted">Not delegated.</p>
    {/if}
    {#if $pillarReward}
      <div class="flex items-center justify-between text-sm">
        <p class="text-muted">Uncollected reward <span class="font-mono text-text">{formatAmount($pillarReward.znn, 8)} ZNN</span> · <span class="font-mono text-text">{formatAmount($pillarReward.qsr, 8)} QSR</span></p>
        <Button variant="primary" disabled={rewardZero} on:click={collect}>Collect</Button>
      </div>
    {/if}
  </section>

  <section class="space-y-3 rounded-lg border border-border bg-surface p-4">
    <div class="flex items-center justify-between gap-3">
      <h2 class="text-sm font-medium text-text">Pillars</h2>
      <span class="text-xs text-muted">Sorted by Rank</span>
    </div>
    <Input bind:value={search} placeholder="Search pillars" ariaLabel="search pillars" />

    <div class="space-y-1">
      {#each filtered as p}
        <div class="flex items-center justify-between gap-3 rounded-md border border-transparent px-2 py-2 hover:border-border hover:bg-elevated">
          <div class="flex min-w-0 items-baseline gap-3">
            <span class="shrink-0 font-mono text-xs text-muted">#{p.rank}</span>
            <span class="truncate text-sm text-text">{p.name}</span>
            {#if p.name === $delegation?.name}<span class="shrink-0 rounded bg-accent/15 px-1.5 py-0.5 text-[10px] font-medium text-accent">current</span>{/if}
          </div>
          <div class="flex shrink-0 items-center gap-4">
            <span class="text-xs text-accent">{p.delegateRewardPercent}% APR</span>
            <span class="font-mono text-xs text-muted">{formatAmount(p.weight, 8)} ZNN</span>
            <Button variant="primary" on:click={() => delegate(p.name)} aria-label={`delegate to ${p.name}`}>Delegate</Button>
          </div>
        </div>
      {/each}
      {#if filtered.length === 0}<p class="text-xs text-muted">No pillars.</p>{/if}
    </div>
  </section>

  {#if error}<p class="text-sm text-error" role="alert">{error}</p>{/if}

  {#if $tx.status === 'preparing'}<p class="text-muted">Preparing… (PoW if required)</p>{/if}
  {#if $tx.status === 'error'}<p class="text-error" role="alert">{$tx.error}</p>{/if}
</div>
