// frontend/src/components/TxResult.vue
<script setup lang="ts">
import { ref } from 'vue'
import { storeToRefs } from 'pinia'
import { Button } from 'nom-ui'
import { useTxStore } from '../stores/tx'
import { ClipboardSetText } from '../../wailsjs/runtime/runtime'

const tx = useTxStore()
const { hash } = storeToRefs(tx)
const copied = ref(false)

async function copy() {
  await ClipboardSetText(hash.value)
  copied.value = true
  setTimeout(() => (copied.value = false), 1200)
}
</script>

<template>
  <div class="space-y-2 rounded border border-success/40 bg-card p-4">
    <p class="text-success">Transaction published</p>
    <div class="break-all font-mono text-xs">{{ hash }}</div>
    <Button variant="ghost" size="xs" @click="copy">{{
      copied ? 'Copied' : 'Copy hash'
    }}</Button>
  </div>
</template>

// frontend/src/lib/components/TxResult.svelte
<script lang="ts">
  import { tx } from '../stores/tx'
  import { ClipboardSetText } from '../../../wailsjs/runtime/runtime'
  let copied = false
  async function copy() { await ClipboardSetText($tx.hash); copied = true; setTimeout(() => (copied = false), 1200) }
</script>
<div class="rounded border border-success/40 bg-surface p-4 space-y-2">
  <p class="text-success">Transaction published</p>
  <div class="font-mono text-xs break-all">{$tx.hash}</div>
  <button class="rounded bg-accent/20 px-2 py-1 text-xs text-accent" on:click={copy}>{copied ? 'Copied' : 'Copy hash'}</button>
</div>
