// frontend/src/routes/Create.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { generateMnemonic, importMnemonic, unlock } from '../lib/stores/wallet'
  import { view } from '../lib/stores/nav'

  let step = 1
  let mnemonic = ''
  let words: string[] = []
  let error = ''

  // backup-verify: 3 randomly chosen distinct positions in the phrase
  let positions: number[] = []
  let answers: Record<number, string> = {}

  let name = ''
  let password = ''
  let confirm = ''

  onMount(async () => {
    try {
      mnemonic = await generateMnemonic()
      words = mnemonic.split(/\s+/)
      const idx = new Set<number>()
      while (idx.size < 3) idx.add(Math.floor(Math.random() * words.length))
      positions = [...idx].sort((a, b) => a - b)
    } catch (e: any) { error = e?.message ?? String(e) }
  })

  $: verifyOk = positions.length === 3 && positions.every((p) => (answers[p] ?? '').trim() === words[p])
  $: canCreate = name.trim() !== '' && password.length > 0 && password === confirm

  function fileName(): string {
    return name.endsWith('.dat') ? name : name + '.dat'
  }

  async function finish() {
    error = ''
    try {
      const fn = fileName()
      await importMnemonic(fn, password, mnemonic)
      await unlock(fn, password)
    } catch (e: any) { error = e?.message ?? String(e) }
  }
</script>

<div class="mx-auto mt-12 w-[32rem] space-y-4">
  <h1 class="text-xl">Create wallet</h1>

  {#if step === 1}
    <p class="text-warn text-sm">Write these 24 words down and store them safely. Anyone with them controls your funds. They are shown only once.</p>
    <div class="grid grid-cols-3 gap-2 rounded bg-surface p-3 font-mono text-sm">
      {#each words as wd, i}<div><span class="text-muted">{i + 1}.</span> {wd}</div>{/each}
    </div>
    <button class="w-full rounded bg-accent py-2 text-bg" on:click={() => (step = 2)}>I've backed it up</button>
  {:else if step === 2}
    <p class="text-sm text-muted">Confirm your backup — enter these words:</p>
    {#each positions as p}
      <label class="block text-sm text-muted">Word #{p + 1}
        <input class="mt-1 w-full rounded bg-surface px-3 py-2 font-mono" bind:value={answers[p]} aria-label={`word ${p + 1}`} />
      </label>
    {/each}
    <button class="w-full rounded bg-accent py-2 text-bg disabled:opacity-50" disabled={!verifyOk} on:click={() => (step = 3)}>Continue</button>
  {:else}
    <label class="block text-sm text-muted">Wallet name<input class="mt-1 w-full rounded bg-surface px-3 py-2" bind:value={name} aria-label="wallet name" /></label>
    <label class="block text-sm text-muted">Password<input type="password" class="mt-1 w-full rounded bg-surface px-3 py-2" bind:value={password} aria-label="password" /></label>
    <label class="block text-sm text-muted">Confirm password<input type="password" class="mt-1 w-full rounded bg-surface px-3 py-2" bind:value={confirm} aria-label="confirm password" /></label>
    <button class="w-full rounded bg-accent py-2 text-bg disabled:opacity-50" disabled={!canCreate} on:click={finish}>Create wallet</button>
  {/if}

  <button class="text-xs text-muted" on:click={() => view.set('unlock')}>Cancel</button>
  {#if error}<p class="text-error" role="alert">{error}</p>{/if}
</div>

// frontend/src/views/Create.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { Card, CardContent, Input, Button } from 'nom-ui'
import { useWalletStore } from '../stores/wallet'

const wallet = useWalletStore()
const router = useRouter()

const step = ref(1)
const mnemonic = ref('')
const words = ref<string[]>([])
const positions = ref<number[]>([])
const answers = ref<Record<number, string>>({})
const name = ref('')
const password = ref('')
const confirm = ref('')
const error = ref('')

onMounted(async () => {
  try {
    mnemonic.value = await wallet.generateMnemonic()
    words.value = mnemonic.value.split(/\s+/)
    const idx = new Set<number>()
    while (idx.size < 3) idx.add(Math.floor(Math.random() * words.value.length))
    positions.value = [...idx].sort((a, b) => a - b)
  } catch (e: any) {
    error.value = e?.message ?? String(e)
  }
})

const verifyOk = computed(
  () => positions.value.length === 3 && positions.value.every((p) => (answers.value[p] ?? '').trim() === words.value[p]),
)
const canCreate = computed(() => name.value.trim() !== '' && password.value.length > 0 && password.value === confirm.value)

async function finish() {
  error.value = ''
  try {
    // `name` is now a display name; the backend assigns a uuid keystore filename.
    // Capture the returned meta and unlock by its real id.
    const meta = await wallet.importMnemonic(name.value.trim(), password.value, mnemonic.value)
    await wallet.unlock(meta.id, password.value)
    router.push('/home')
  } catch (e: any) {
    error.value = e?.message ?? String(e)
  } finally {
    password.value = ''
    confirm.value = ''
  }
}
</script>

<template>
  <main class="grid min-h-screen place-items-center bg-background p-8">
    <Card class="w-[32rem]">
      <CardContent class="space-y-4 p-6">
        <h1 class="text-xl text-foreground">Create wallet</h1>

        <template v-if="step === 1">
          <p class="text-sm text-destructive">
            Write these {{ words.length }} words down and store them safely. Anyone with them controls your funds.
            They are shown only once.
          </p>
          <div class="grid grid-cols-3 gap-2 rounded bg-background p-3 font-mono text-sm text-foreground">
            <div v-for="(wd, i) in words" :key="i"><span class="text-muted-foreground">{{ i + 1 }}.</span> {{ wd }}</div>
          </div>
          <Button class="w-full" @click="step = 2">I've backed it up</Button>
        </template>

        <template v-else-if="step === 2">
          <p class="text-sm text-muted-foreground">Confirm your backup — enter these words:</p>
          <label v-for="p in positions" :key="p" class="block text-sm text-muted-foreground">
            Word #{{ p + 1 }}
            <Input v-model="answers[p]" :aria-label="`word ${p + 1}`" class="mt-1 font-mono" />
          </label>
          <Button class="w-full" :disabled="!verifyOk" @click="step = 3">Continue</Button>
        </template>

        <template v-else>
          <Input v-model="name" placeholder="Wallet name" aria-label="wallet name" />
          <Input v-model="password" type="password" placeholder="Password" aria-label="password" />
          <Input v-model="confirm" type="password" placeholder="Confirm password" aria-label="confirm password" />
          <Button class="w-full" :disabled="!canCreate" @click="finish">Create wallet</Button>
        </template>

        <button class="text-xs text-muted-foreground" @click="router.push('/unlock')">Cancel</button>
        <p v-if="error" class="text-sm text-destructive" role="alert">{{ error }}</p>
      </CardContent>
    </Card>
  </main>
</template>
