// frontend/src/routes/ImportMnemonic.svelte
<script lang="ts">
  import { importMnemonic, unlock } from '../lib/stores/wallet'
  import { view } from '../lib/stores/nav'
  let mnemonic = ''
  let name = ''
  let password = ''
  let confirm = ''
  let error = ''
  $: wordCount = mnemonic.trim().split(/\s+/).filter(Boolean).length
  $: looksValid = wordCount === 12 || wordCount === 24
  $: canImport = looksValid && name.trim() !== '' && password.length > 0 && password === confirm
  async function doImport() {
    error = ''
    const file = name.endsWith('.dat') ? name : name + '.dat'
    try { await importMnemonic(file, password, mnemonic.trim()); await unlock(file, password) }
    catch (e: any) { error = e?.message ?? String(e) }
  }
</script>
<div class="mx-auto mt-12 w-[32rem] space-y-4">
  <h1 class="text-xl">Import from mnemonic</h1>
  <textarea class="w-full rounded bg-surface p-3 font-mono text-sm" rows="3" placeholder="word1 word2 …" bind:value={mnemonic} aria-label="mnemonic"></textarea>
  {#if mnemonic && !looksValid}<p class="text-xs text-error">Expected 12 or 24 words ({wordCount})</p>{/if}
  <label class="block text-sm text-muted">Wallet name<input class="mt-1 w-full rounded bg-surface px-3 py-2" bind:value={name} aria-label="wallet name" /></label>
  <label class="block text-sm text-muted">Password<input type="password" class="mt-1 w-full rounded bg-surface px-3 py-2" bind:value={password} aria-label="password" /></label>
  <label class="block text-sm text-muted">Confirm<input type="password" class="mt-1 w-full rounded bg-surface px-3 py-2" bind:value={confirm} aria-label="confirm password" /></label>
  <button class="w-full rounded bg-accent py-2 text-bg disabled:opacity-50" disabled={!canImport} on:click={doImport} aria-label="Import">Import</button>
  <button class="text-xs text-muted" on:click={() => view.set('unlock')}>Cancel</button>
  {#if error}<p class="text-error" role="alert">{error}</p>{/if}
</div>

// frontend/src/views/ImportMnemonic.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useRouter } from 'vue-router'
import { Card, CardContent, Input, Button } from 'nom-ui'
import { useWalletStore } from '../stores/wallet'

const wallet = useWalletStore()
const router = useRouter()
const mnemonic = ref('')
const name = ref('')
const password = ref('')
const confirm = ref('')
const error = ref('')

const wordCount = computed(() => mnemonic.value.trim().split(/\s+/).filter(Boolean).length)
const looksValid = computed(() => wordCount.value === 12 || wordCount.value === 24)
const canImport = computed(
  () => looksValid.value && name.value.trim() !== '' && password.value.length > 0 && password.value === confirm.value,
)

async function doImport() {
  error.value = ''
  const file = name.value.endsWith('.dat') ? name.value : name.value + '.dat'
  try {
    await wallet.importMnemonic(file, password.value, mnemonic.value.trim())
    await wallet.unlock(file, password.value)
    router.push('/home')
  } catch (e: any) {
    error.value = e?.message ?? String(e)
  } finally {
    password.value = ''
    confirm.value = ''
  }
}
</script>

<template>
  <main class="grid min-h-screen place-items-center bg-background p-8">
    <Card class="w-[32rem]">
      <CardContent class="space-y-4 p-6">
        <h1 class="text-xl text-foreground">Import from mnemonic</h1>
        <textarea
          v-model="mnemonic"
          rows="3"
          placeholder="word1 word2 …"
          aria-label="mnemonic"
          class="w-full rounded border border-border bg-background p-3 font-mono text-sm text-foreground"></textarea>
        <p v-if="mnemonic && !looksValid" class="text-xs text-destructive">Expected 12 or 24 words ({{ wordCount }})</p>
        <Input v-model="name" placeholder="Wallet name" aria-label="wallet name" />
        <Input v-model="password" type="password" placeholder="Password" aria-label="password" />
        <Input v-model="confirm" type="password" placeholder="Confirm password" aria-label="confirm password" />
        <Button class="w-full" :disabled="!canImport" aria-label="Import" @click="doImport">Import</Button>
        <button class="text-xs text-muted-foreground" @click="router.push('/unlock')">Cancel</button>
        <p v-if="error" class="text-sm text-destructive" role="alert">{{ error }}</p>
      </CardContent>
    </Card>
  </main>
</template>
