// frontend/src/routes/Unlock.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte'
  import * as W from '../../wailsjs/go/app/WalletService'
  import { unlock } from '../lib/stores/wallet'
  import { view } from '../lib/stores/nav'
  import PasswordInput from '../lib/components/PasswordInput.svelte'
  import WalletPicker from '../lib/components/WalletPicker.svelte'

  const dispatch = createEventDispatcher()
  let wallets: { name: string; baseAddress: string }[] = []
  let selected = ''
  let password = ''
  let error = ''
  let busy = false

  async function refresh() {
    wallets = ((await W.ListWallets()) ?? []) as { name: string; baseAddress: string }[]
    if (!selected && wallets[0]) selected = wallets[0].name
  }
  onMount(refresh)

  async function doUnlock() {
    error = ''; busy = true
    try { await unlock(selected, password); dispatch('unlocked') }
    catch (e: any) { error = e?.message ?? String(e) }
    finally { busy = false; password = '' }
  }

  async function doImport() {
    error = ''
    try {
      const path = await W.PickKeystoreFile()
      if (!path) return            // cancelled
      await W.ImportKeystore(path)
      await refresh()
    } catch (e: any) { error = e?.message ?? String(e) }
  }
</script>

<div class="mx-auto mt-16 w-[28rem] space-y-4">
  <h1 class="text-xl">Unlock wallet</h1>
  {#if wallets.length === 0}
    <p class="text-muted">No wallets yet. Import a keystore to begin.</p>
  {:else}
    <WalletPicker {wallets} bind:selected />
    <PasswordInput bind:value={password} />
    <button class="w-full rounded bg-accent py-2 text-bg disabled:opacity-50"
      disabled={busy || !selected} on:click={doUnlock} aria-label="Unlock">Unlock</button>
  {/if}
  <button class="w-full rounded border border-muted/40 py-2 text-muted" on:click={doImport}>Import keystore…</button>
  <button class="w-full rounded border border-muted/40 py-2 text-muted" on:click={() => view.set('create')}>Create new wallet</button>
  <button class="w-full rounded border border-muted/40 py-2 text-muted" on:click={() => view.set('import')}>Import mnemonic</button>
  {#if error}<p class="text-error" role="alert">{error}</p>{/if}
</div>

// frontend/src/views/Unlock.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { Card, CardContent, Input, Button } from 'nom-ui'
import { useWalletStore } from '../stores/wallet'

const wallet = useWalletStore()
const router = useRouter()
const selected = ref('')
const password = ref('')
const error = ref('')
const busy = ref(false)

onMounted(async () => {
  await wallet.loadWallets()
  if (!selected.value && wallet.wallets[0]) selected.value = wallet.wallets[0]
})

async function doUnlock() {
  error.value = ''
  busy.value = true
  try {
    await wallet.unlock(selected.value, password.value)
    router.push('/home')
  } catch (e: any) {
    error.value = e?.message ?? String(e)
  } finally {
    busy.value = false
    password.value = ''
  }
}

async function doImport() {
  error.value = ''
  try {
    const path = await wallet.pickKeystoreFile()
    if (!path) return
    await wallet.importKeystore(path)
    if (!selected.value && wallet.wallets[0]) selected.value = wallet.wallets[0]
  } catch (e: any) {
    error.value = e?.message ?? String(e)
  }
}
</script>

<template>
  <main class="grid min-h-screen place-items-center bg-background p-8">
    <Card class="w-96">
      <CardContent class="space-y-4 p-6">
        <h1 class="text-xl text-foreground">Unlock wallet</h1>
        <p v-if="wallet.wallets.length === 0" class="text-muted-foreground">
          No wallets yet. Import a keystore to begin.
        </p>
        <template v-else>
          <select
            v-model="selected"
            aria-label="wallet"
            class="w-full rounded border border-border bg-background px-3 py-2 text-foreground">
            <option v-for="w in wallet.wallets" :key="w" :value="w">{{ w }}</option>
          </select>
          <Input v-model="password" type="password" placeholder="Password" aria-label="password" @keyup.enter="doUnlock" />
          <Button class="w-full" :disabled="busy || !selected" aria-label="Unlock" @click="doUnlock">Unlock</Button>
        </template>
        <Button variant="outline" class="w-full" @click="doImport">Import keystore…</Button>
        <Button variant="outline" class="w-full" @click="router.push('/create')">Create new wallet</Button>
        <Button variant="outline" class="w-full" @click="router.push('/import')">Import mnemonic</Button>
        <p v-if="error" class="text-sm text-destructive" role="alert">{{ error }}</p>
      </CardContent>
    </Card>
  </main>
</template>
